name: Fly Deploy
on: 
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 4 1 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions@master
        with:
          args: "deploy"